const {test}=require('node:test');const assert=require('node:assert/strict');const {Readable}=require('node:stream');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');const crypto=require('node:crypto');
const {createHandler,MemoryTestLimiter}=require('../backend/quote-server.cjs');
test('adapter and details-only handler complete real multipart serialization with injected transport only',async()=>{
 const sent=[];const handler=createHandler({mode:'test',strategy:'provider-bounded',recipient:'intake@example.invalid',origin:'https://preview.example',tokenSecret:'synthetic-test-secret-32-characters',limiter:new MemoryTestLimiter(),transport:{renderVersion:'asi-quote-v1',idempotencyWindowMs:86400000,submit:async x=>{sent.push(x);return {accepted:true,providerMessageId:'mock-message'}}}});
 const storage=new Map(),window={ASI_CONFIG:{quoteMode:'production',quoteEndpoint:'/api/quote'},location:{href:'https://preview.example/quote.html',origin:'https://preview.example'},crypto,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)}};
 const fetch=async(url,opts)=>{const serialized=new Request(url,{method:'POST',body:opts.body});const body=Buffer.from(await serialized.arrayBuffer());const req=Readable.from([body]);req.method='POST';req.url=new URL(url).pathname;req.headers={origin:'https://preview.example','content-type':serialized.headers.get('content-type')};req.socket={remoteAddress:'192.0.2.1'};let status,data;const res={writeHead(s){status=s},end(v){this.writableEnded=true;data=JSON.parse(v)}};await handler(req,res);return {ok:status>=200&&status<300,json:async()=>data};};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../site/js/quote-adapter.js'),'utf8'),{window,URL,FormData,AbortController,setTimeout,clearTimeout,fetch});
 const fields={service:'Plan Review',name:'Synthetic Test',company:'',email:'test@example.invalid',phone:'',location:'Synthetic City',projectType:'Residential',squareFootage:'',permitStatus:'',scope:'Synthetic details only',timing:'',source:'',consent:true,consentVersion:'asi-project-inquiry-v1',website:''};
 const result=await window.ASI_QUOTE_SUBMIT(fields,[]);assert.equal(result.ok,true);assert.match(result.message,/submitted for email delivery/);assert.equal(sent.length,1);assert.equal(sent[0].fields.consent,true);assert.equal(sent[0].recipient,'intake@example.invalid');assert.equal(storage.size,0);
});
