const {test}=require('node:test');const assert=require('node:assert/strict');const {Readable}=require('node:stream');const {randomUUID}=require('node:crypto');
const {createHandler,parseMultipart,validate,issueToken,verifyToken,MemoryTestStore,MemoryTestLimiter,MAX_BODY}=require('../backend/quote-server.cjs');
const secret='synthetic-test-only-secret-32-characters',origin='https://preview.example';
function payload(overrides={}){const p={service:'Plan Review',name:'Synthetic Test',company:'',email:'test@example.invalid',phone:'',location:'Synthetic City',projectType:'Residential',squareFootage:'',permitStatus:'',scope:'Synthetic project details',timing:'',source:'',submissionId:randomUUID(),consent:true,consentVersion:'asi-project-inquiry-v1',website:'',token:'',...overrides};if(!Object.hasOwn(overrides,'token')){try{p.token=issueToken(secret,validate(p));}catch{p.token='invalid';}}return p;}
function multipart(p,extra=''){return Buffer.from('--BOUNDARY\r\nContent-Disposition: form-data; name="payload"\r\n\r\n'+JSON.stringify(p)+extra+'\r\n--BOUNDARY--\r\n')}
function config(overrides={}){return {mode:'test',strategy:'durable',recipient:'intake@example.invalid',origin,tokenSecret:secret,store:new MemoryTestStore(),limiter:new MemoryTestLimiter(),transport:{submit:async()=>({accepted:true,providerMessageId:'mock-message'})},...overrides}}
async function request(handler,body,overrides={}){const chunks=Array.isArray(body)?body:[body||Buffer.alloc(0)];const req=Readable.from(chunks);req.method='POST';req.url='/api/quote';req.headers={origin,'content-type':'multipart/form-data; boundary=BOUNDARY',...overrides.headers};req.socket={remoteAddress:'192.0.2.1'};if(overrides.url)req.url=overrides.url;if(overrides.method)req.method=overrides.method;let status,data,headers;const res={writeHead(s,h){status=s;headers=h},end(value){this.writableEnded=true;data=JSON.parse(value)}};await handler(req,res);return {status,data,headers}}
test('default and in-memory production dependencies fail closed',async()=>{for(const handler of [createHandler(),createHandler(config({mode:'production'}))]){const r=await request(handler,multipart(payload()));assert.equal(r.status,503);assert.equal(r.data.ok,false)}});
test('details-only confirmed provider acceptance is not inbox receipt',async()=>{let sent;const h=createHandler(config({transport:{submit:async p=>{sent=p;return {accepted:true,providerMessageId:'mock'}}}}));const r=await request(h,multipart(payload()));assert.equal(r.status,200);assert.equal(r.data.deliveryStage,'submitted_for_email_delivery');assert.equal(sent.recipient,'intake@example.invalid');assert.equal(sent.fields.consent,true);assert.equal(r.headers['Cache-Control'],'no-store')});
test('reject missing/tampered consent, enum, email, CRLF, unknown fields, honeypot',async()=>{for(const change of [{consent:false},{consent:'true'},{consentVersion:'other'},{service:'Fake'},{email:'bad'},{name:'Name\r\nBcc: bad'},{recipient:'attacker@example.invalid'},{website:'spam'}]){const r=await request(createHandler(config()),multipart(payload(change)));assert.equal(r.status,422,JSON.stringify(change))}});
test('reject any file part, duplicate payload, malformed multipart or JSON',async()=>{const p=payload();for(const extra of ['\r\n--BOUNDARY\r\nContent-Disposition: form-data; name="files"; filename="test.txt"\r\n\r\nbody','\r\n--BOUNDARY\r\nContent-Disposition: form-data; name="payload"\r\n\r\n{}']){const r=await request(createHandler(config()),multipart(p,extra));assert.equal(r.status,422)}for(const body of [Buffer.from('malformed'),Buffer.from('--BOUNDARY\r\nContent-Disposition: form-data; name="payload"\r\n\r\n{broken}\r\n--BOUNDARY--\r\n')]){assert.equal((await request(createHandler(config()),body)).status,400)}});
test('streaming chunked and declared body limits apply',async()=>{let r=await request(createHandler(config()),[Buffer.alloc(MAX_BODY/2),Buffer.alloc(MAX_BODY/2+1)]);assert.equal(r.status,413);r=await request(createHandler(config()),Buffer.from(''),{headers:{'content-length':String(MAX_BODY+1)}});assert.equal(r.status,413)});
test('token expiration/tampering and foreign origin rejected',async()=>{for(const token of ['invalid','expired.invalid']){assert.equal((await request(createHandler(config()),multipart(payload({token})))).status,403)}assert.equal((await request(createHandler(config()),multipart(payload()),{headers:{origin:'https://foreign.example'}})).status,403)});
test('same identity/content returns original receipt, conflicts reject',async()=>{let calls=0;const h=createHandler(config({transport:{submit:async()=>{calls++;return {accepted:true,providerMessageId:'mock'}}}}));const p=payload();const first=await request(h,multipart(p));const second=await request(h,multipart(p));assert.equal(first.data.receiptId,second.data.receiptId);assert.equal(calls,1);const changed={...p,scope:'changed'};changed.token=issueToken(secret,validate(changed));assert.equal((await request(h,multipart(changed))).status,409)});
test('concurrent duplicates never send twice',async()=>{let release,calls=0;const h=createHandler(config({transport:{submit:()=>{calls++;return new Promise(r=>{release=r})}}}));const p=payload(),first=request(h,multipart(p));while(!release)await new Promise(r=>setImmediate(r));const second=await request(h,multipart(p));assert.equal(second.status,409);release({accepted:true,providerMessageId:'mock'});assert.equal((await first).status,200);assert.equal(calls,1)});
test('provider errors and fake successes never confirm, ambiguous retry does not resend',async()=>{for(const response of [null,{accepted:false},{accepted:true}]){let calls=0;const h=createHandler(config({transport:{submit:async()=>{calls++;return response}}}));const p=payload();assert.equal((await request(h,multipart(p))).status,503);assert.equal((await request(h,multipart(p))).status,409);assert.equal(calls,1)}});
test('provider timeout and exceptions retain uncertain state; safe logs contain no PII',async()=>{const logs=[];for(const submit of [async()=>{throw Error('private customer data')},()=>new Promise(()=>{})]){const h=createHandler(config({timeoutMs:5,log:item=>logs.push(item),transport:{submit}}));const r=await request(h,multipart(payload()));assert.equal(r.status,503)}const serialized=JSON.stringify(logs);assert(!serialized.includes('Synthetic'));assert(!serialized.includes('private'));assert(!serialized.includes('192.0.2.1'));assert(logs.every(x=>Object.keys(x).sort().join()==='code,requestId,status'))});
test('rate limits and unavailable dependencies do not send',async()=>{assert.equal((await request(createHandler(config({limiter:new MemoryTestLimiter(0)})),multipart(payload()))).status,429);assert.equal((await request(createHandler(config({store:{reserve:async()=>{throw Error('offline')},confirm(){},uncertain(){}}})),multipart(payload()))).status,503)});
function boundedConfig(overrides={}){return config({strategy:'provider-bounded',store:undefined,transport:{idempotencyWindowMs:86400000,renderVersion:'asi-quote-v1',submit:async()=>({accepted:true,providerMessageId:'mock'})},...overrides})}
test('token issuance binds ID, canonical hash, render version and expiration',async()=>{const p=payload({token:''}),h=createHandler(boundedConfig());const response=await request(h,multipart(p),{url:'/api/quote/token'});assert.equal(response.status,200);assert.equal(response.data.expiresIn,1800);p.token=response.data.token;assert(verifyToken(p.token,secret,validate(p)));assert(!verifyToken(p.token,secret,validate({...p,scope:'changed'})));assert(!verifyToken(p.token,secret,validate(p),Date.now()+1800001));assert.equal((await request(h,multipart({...p,scope:'changed'}))).status,403)});
test('provider-bounded retries after uncertain response preserve exact provider key/body across restart',async()=>{const effects=new Map(),calls=[];let fail=true;const transport={idempotencyWindowMs:86400000,renderVersion:'asi-quote-v1',submit:async data=>{calls.push(JSON.stringify({recipient:data.recipient,fields:data.fields,key:data.idempotencyKey,renderVersion:data.renderVersion}));if(!effects.has(data.idempotencyKey))effects.set(data.idempotencyKey,{accepted:true,providerMessageId:'mock'});if(fail){fail=false;throw Error('acceptance response lost')}return effects.get(data.idempotencyKey)}};const p=payload();assert.equal((await request(createHandler(boundedConfig({transport})),multipart(p))).status,503);const retried=await request(createHandler(boundedConfig({transport})),multipart(p));assert.equal(retried.status,200);assert.equal(retried.data.receiptId,p.submissionId);assert.equal(effects.size,1);assert.equal(calls[0],calls[1])});
test('provider-bounded concurrent duplicates use one active transport and same original reference',async()=>{let calls=0,release;const transport={idempotencyWindowMs:86400000,renderVersion:'asi-quote-v1',submit:()=>{calls++;return new Promise(r=>{release=r})}};const h=createHandler(boundedConfig({transport})),p=payload();const first=request(h,multipart(p));while(!release)await new Promise(r=>setImmediate(r));assert.equal((await request(h,multipart(p))).status,409);release({accepted:true,providerMessageId:'mock'});assert.equal((await first).data.receiptId,p.submissionId);assert.equal((await request(h,multipart(p))).data.receiptId,p.submissionId);assert.equal(calls,1)});
test('provider-bounded dependency capabilities, delivery quota and file MIME fail closed',async()=>{assert.equal((await request(createHandler(boundedConfig({transport:{submit:async()=>({accepted:true,providerMessageId:'mock'})}})),multipart(payload()))).status,503);const limiter={consume:async({kind})=>kind!=='delivery'};assert.equal((await request(createHandler(boundedConfig({limiter})),multipart(payload()))).status,429);const file='\r\n--BOUNDARY\r\nContent-Disposition: form-data; name="unexpected"; filename="test.txt"\r\nContent-Type: text/plain\r\n\r\nbody';const response=await request(createHandler(boundedConfig()),multipart(payload(),file));assert.equal(response.data.code,'FILES_DEFERRED')});
test('expired content-bound token cannot submit or silently renew',async()=>{let calls=0;const transport={idempotencyWindowMs:86400000,renderVersion:'asi-quote-v1',submit:async()=>{calls++;return {accepted:true,providerMessageId:'mock'}}};const p=payload();p.token=issueToken(secret,validate(p),Date.now()-1800001);const response=await request(createHandler(boundedConfig({transport})),multipart(p));assert.equal(response.status,403);assert.equal(calls,0)});
test('hung limiter dependencies release active request capacity after bounded deadlines',async()=>{let hang=true;const limiter={consume:()=>hang?new Promise(()=>{}):Promise.resolve(true)};const h=createHandler(boundedConfig({limiter,dependencyTimeoutMs:5}));const results=await Promise.all(Array.from({length:4},()=>request(h,multipart(payload()))));assert(results.every(r=>r.status===503));hang=false;assert.equal((await request(h,multipart(payload()))).status,200)});
test('hung durable store reserve/confirm fail without a receipt',async()=>{for(const method of ['reserve','confirm']){const store=new MemoryTestStore();store[method]=()=>new Promise(()=>{});const h=createHandler(config({store,dependencyTimeoutMs:5}));const r=await request(h,multipart(payload()));assert.equal(r.status,503);assert.equal(r.data.ok,false)}});
test('pre-send delivery limiter rejection or timeout releases bounded identity for safe retry',async()=>{for(const failure of ['reject','timeout']){let first=true,calls=0;const limiter={consume:async({kind})=>{if(kind==='delivery'&&first){first=false;if(failure==='reject')throw Error('unavailable');return new Promise(()=>{})}return true}};const transport={idempotencyWindowMs:86400000,renderVersion:'asi-quote-v1',submit:async()=>{calls++;return {accepted:true,providerMessageId:'mock'}}};const h=createHandler(boundedConfig({limiter,transport,dependencyTimeoutMs:5})),p=payload();assert.equal((await request(h,multipart(p))).status,503);assert.equal(calls,0);assert.equal((await request(h,multipart(p))).status,200);assert.equal(calls,1)}});
