const {test}=require('node:test');const assert=require('node:assert/strict');const {randomUUID}=require('node:crypto');
const {createResendTransport,renderEmail}=require('../backend/resend-transport.cjs');
const {SingleInstanceLimiter}=require('../backend/single-instance-limiter.cjs');
const {configuration,createRuntime}=require('../backend/runtime.cjs');
const sender='sender@example.invalid',recipient='intake@example.invalid',providerId='12345678-1234-4234-8234-123456789abc';
function fields(){return {service:'Plan Review',name:'Synthetic <b>Client</b>',company:'',email:'client@example.invalid',phone:'',location:'Synthetic City',projectType:'Residential',squareFootage:'',permitStatus:'',scope:'<script>alert(1)</script>\nSynthetic details',timing:'',source:'',consent:true,consentVersion:'asi-project-inquiry-v1'}}
function input(){return {recipient,fields:fields(),idempotencyKey:'asi-quote/'+randomUUID(),renderVersion:'asi-quote-v1',signal:new AbortController().signal}}
function transport(overrides={}){return createResendTransport({enabled:true,apiKey:'re_synthetic_test_only',sender,recipient,fetchImpl:async()=>new Response(JSON.stringify({id:providerId}),{status:200}),...overrides})}
function environment(){return {ASI_ENABLE_DELIVERY:'true',ASI_RELEASE_APPROVED:'true',ASI_PROVIDER_APPROVED:'true',ASI_SINGLE_INSTANCE_VERIFIED:'true',ASI_PROVIDER_HARD_QUOTA_VERIFIED:'true',ASI_INGRESS_POLICY_VERIFIED:'true',ASI_INSTANCE_COUNT:'1',ASI_NOTIFICATION_EMAIL:recipient,ASI_VERIFIED_SENDER:sender,ASI_PUBLIC_ORIGIN:'https://preview.example',ASI_TOKEN_SIGNING_SECRET:'synthetic_test_only_signing_secret_43_characters',RESEND_API_KEY:'re_synthetic_test_only'}}
test('Resend transport is disabled by default and never calls fetch',async()=>{let calls=0;const t=createResendTransport({fetchImpl:async()=>{calls++}});assert.equal(t.authorized,false);await assert.rejects(t.submit(input()));assert.equal(calls,0)});
test('Resend uses official API, fixed routing, Reply-To and stable idempotent JSON body',async()=>{const calls=[],t=transport({fetchImpl:async(url,opts)=>{calls.push({url,opts});return new Response(JSON.stringify({id:providerId}))}}),request=input();assert.deepEqual(await t.submit(request),{accepted:true,providerMessageId:providerId});await t.submit(request);assert.equal(calls[0].url,'https://api.resend.com/emails');assert.equal(calls[0].opts.method,'POST');assert.equal(calls[0].opts.redirect,'error');assert.equal(calls[0].opts.headers['Idempotency-Key'],request.idempotencyKey);assert.equal(calls[0].opts.headers.Authorization,'Bearer re_synthetic_test_only');assert.equal(calls[0].opts.body,calls[1].opts.body);const body=JSON.parse(calls[0].opts.body);assert.equal(body.from,sender);assert.deepEqual(body.to,[recipient]);assert.equal(body.reply_to,'client@example.invalid');assert.equal(body.html,undefined);assert.equal(body.cc,undefined);assert.match(body.text,/American Standard Construction & Safety Consulting LLC/);assert.match(body.text,/<script>/);assert(!body.subject.includes('Synthetic'))});
test('transport rejects routing, reply-to header injection and renderer-version changes',async()=>{let calls=0;const t=transport({fetchImpl:async()=>{calls++}});await assert.rejects(t.submit({...input(),recipient:'wrong@example.invalid'}));await assert.rejects(t.submit({...input(),fields:{...fields(),email:'client@example.invalid\r\nBcc: other@example.invalid'}}));await assert.rejects(t.submit({...input(),renderVersion:'other'}));assert.equal(calls,0)});
test('provider error/redirect/quota/invalid success bodies are redacted and never acknowledged',async()=>{for(const response of [new Response('PRIVATE CONTACT DATA',{status:401}),new Response('PRIVATE CONTACT DATA',{status:409}),new Response('PRIVATE CONTACT DATA',{status:429}),new Response('PRIVATE CONTACT DATA',{status:503}),new Response('{}',{status:302}),new Response('<html>bad</html>'),new Response('{"id":"wrong"}'),new Response('x'.repeat(4097))]){const t=transport({fetchImpl:async()=>response});await assert.rejects(t.submit(input()),e=>{assert(!String(e).includes('PRIVATE'));assert(!String(e).includes('CONTACT'));return true})}});
test('provider network errors/timeouts are bounded, aborted and redact secrets',async()=>{const broken=transport({fetchImpl:async()=>{throw Error('secret re_private customer@example.invalid')}});await assert.rejects(broken.submit(input()),e=>!String(e).includes('re_private'));let signal;const hung=transport({timeoutMs:5,fetchImpl:async(_,opts)=>{signal=opts.signal;return new Promise(()=>{})}});await assert.rejects(hung.submit(input()),e=>e.code==='PROVIDER_TIMEOUT');assert.equal(signal.aborted,true)});
test('runtime remains disabled without activation and refuses missing approvals or malformed env',()=>{assert.equal(createRuntime({}).enabled,false);for(const key of ['ASI_RELEASE_APPROVED','ASI_PROVIDER_APPROVED','ASI_SINGLE_INSTANCE_VERIFIED','ASI_PROVIDER_HARD_QUOTA_VERIFIED','ASI_INGRESS_POLICY_VERIFIED','RESEND_API_KEY','ASI_TOKEN_SIGNING_SECRET','ASI_NOTIFICATION_EMAIL','ASI_VERIFIED_SENDER']){const env=environment();delete env[key];assert.throws(()=>configuration(env),undefined,key)}for(const changes of [{ASI_INSTANCE_COUNT:'2'},{ASI_PUBLIC_ORIGIN:'http://preview.example'},{ASI_PUBLIC_ORIGIN:'https://preview.example/path'},{ASI_NOTIFICATION_EMAIL:'client@example.invalid\r\nBcc:x'},{ASI_DAILY_DELIVERY_LIMIT:'76'}])assert.throws(()=>configuration({...environment(),...changes}));assert.equal(createRuntime(environment(),{fetchImpl:async()=>{throw Error('must not call on startup')}}).enabled,true)});
test('bounded limiter requires single-instance and provider-hard-quota checks without claiming shared state',async()=>{const unverified=new SingleInstanceLimiter();assert.equal(await unverified.consume({ipKey:'synthetic',kind:'token'}),false);assert.equal(unverified.shared,false);const l=new SingleInstanceLimiter({verifiedSingleInstance:true,providerHardQuotaVerified:true,dailyDeliveryLimit:2});assert.equal(await l.consume({ipKey:'x',kind:'delivery',submissionId:'1'}),true);assert.equal(await l.consume({ipKey:'x',kind:'delivery',submissionId:'1'}),true);assert.equal(await l.consume({ipKey:'x',kind:'delivery',submissionId:'2'}),true);assert.equal(await l.consume({ipKey:'x',kind:'delivery',submissionId:'3'}),false)});
test('bounded limiter enforces burst/sustained/global caps and documents reset behavior',async()=>{let now=0;const l=new SingleInstanceLimiter({verifiedSingleInstance:true,providerHardQuotaVerified:true,now:()=>now});for(let i=0;i<20;i++)assert.equal(await l.consume({ipKey:'x',kind:'token'}),true);assert.equal(await l.consume({ipKey:'x',kind:'inquiry'}),false);now=61000;for(let i=0;i<20;i++)assert.equal(await l.consume({ipKey:'x',kind:'token'}),true);now=122000;for(let i=0;i<20;i++)assert.equal(await l.consume({ipKey:'x',kind:'token'}),true);now=183000;assert.equal(await l.consume({ipKey:'x',kind:'inquiry'}),false);const reset=new SingleInstanceLimiter({verifiedSingleInstance:true,providerHardQuotaVerified:true});assert.equal(await reset.consume({ipKey:'x',kind:'token'}),true);const global=new SingleInstanceLimiter({verifiedSingleInstance:true,providerHardQuotaVerified:true,now:()=>0});for(let i=0;i<120;i++)assert.equal(await global.consume({ipKey:'client'+i,kind:'token'}),true);assert.equal(await global.consume({ipKey:'extra',kind:'token'}),false)});
test('runtime health distinguishes configuration from verified delivery without making provider calls',async()=>{let calls=0;const runtime=createRuntime(environment(),{fetchImpl:async()=>{calls++}});let status,data;runtime.handler({url:'/api/health',method:'GET'},{writeHead(s){status=s},end(s){data=JSON.parse(s)}});assert.equal(status,200);assert.equal(data.deliveryVerified,false);assert.equal(calls,0);createRuntime({}).handler({url:'/api/health',method:'GET'},{writeHead(s){status=s},end(s){data=JSON.parse(s)}});assert.equal(status,503)});
test('operator identification preserves ASI branding and proposed deployment retains safe defaults',()=>{const fs=require('node:fs'),path=require('node:path'),root=path.join(__dirname,'..');for(const name of ['index.html','quote.html','legal/terms.html','legal/privacy.html']){const text=fs.readFileSync(path.join(root,'site',name),'utf8');assert(text.includes('American Standard Construction &amp; Safety Consulting LLC'));assert(text.includes('ASI'));assert(!text.includes('d/b/a'))}const proposal=fs.readFileSync(path.join(root,'deployment/api-proposal.yaml'),'utf8');assert(proposal.includes('preserve_path_prefix: true'));assert(proposal.includes('instance_count: 1'));assert(proposal.includes('deploy_on_push: false'));assert(proposal.includes('value: "false"'));assert(!proposal.includes('RESEND_API_KEY:'));});
test('runtime handler and Resend renderer complete token/send/replay with injected HTTP only',async()=>{const {Readable}=require('node:stream');let sends=0,lastBody;const runtime=createRuntime(environment(),{fetchImpl:async(url,opts)=>{sends++;assert.equal(url,'https://api.resend.com/emails');lastBody=JSON.parse(opts.body);return new Response(JSON.stringify({id:providerId}))}});const data={...fields(),submissionId:randomUUID(),website:'',token:''};async function post(url){const body=Buffer.from('--RUNTIME\r\nContent-Disposition: form-data; name="payload"\r\n\r\n'+JSON.stringify(data)+'\r\n--RUNTIME--\r\n');const req=Readable.from([body]);Object.assign(req,{method:'POST',url,headers:{origin:'https://preview.example','content-type':'multipart/form-data; boundary=RUNTIME'},socket:{remoteAddress:'192.0.2.1'}});let status,response;await runtime.handler(req,{writeHead(s){status=s},end(s){this.writableEnded=true;response=JSON.parse(s)}});return {status,response}}const token=await post('/api/quote/token');assert.equal(token.status,200);assert.equal(sends,0);data.token=token.response.token;const first=await post('/api/quote');assert.equal(first.status,200);assert.equal(first.response.receiptId,data.submissionId);assert.equal(first.response.deliveryStage,'submitted_for_email_delivery');assert.equal((await post('/api/quote')).response.receiptId,data.submissionId);assert.equal(sends,1);assert.equal(lastBody.from,sender);assert.deepEqual(lastBody.to,[recipient]);assert.equal(lastBody.html,undefined)});
test('advertised oversized provider body is cancelled and transport aborted on rejection',async()=>{let cancelled=false,signal;const body=new ReadableStream({start(c){c.enqueue(new TextEncoder().encode('x'))},cancel(){cancelled=true}});const t=transport({fetchImpl:async(_,opts)=>{signal=opts.signal;return new Response(body,{headers:{'content-length':'4097'}})}});await assert.rejects(t.submit(input()));assert.equal(signal.aborted,true);assert.equal(cancelled,true)});
